package constanta

const Page = "PAGE"
const Limit = "LIMIT"
const OrderBy = "ORDER_BY"
const Filter = "FILTER"
const Npwp = "NPWP"
const ID = "ID"
const UpdatedAt = "UPDATED_AT"
const CompanyProfile = "COMPANY_PROFILE"
const Example = "EXAMPLE"
const Company = "COMPANY"
const CompanyBranch = "COMPANY_BRANCH"
const Code = "CODE"
const ProductCategory = "PRODUCT_CATEGORY"
const CompanyDivision = "COMPANY_DIVISION"
const ProductGroup = "PRODUCT_GROUP"
const ParentID = "PARENT_ID"
const Product = "PRODUCT"
const OrderDate = "ORDER_DATE"
const Item = "ITEM"
const OrderNumber = "ORDER_NUMBER"
const SalesOrder = "SALES_ORDER"
const InvoiceNumber = "INVOICE_NUMBER"
